"""Statistical analysis tools."""

from cds.stats.descriptive import correlation, mean, median, stdev, variance
from cds.stats.hypothesis_tests import (
    TestResult,
    bonferroni_corrected_alpha,
    chi2_sf,
    chi_square_gof,
    chi_square_independence,
    cohens_d,
    cramers_v,
    eta_squared_from_f,
    f_sf,
    one_sample_ttest,
    one_way_anova,
    t_sf,
    two_sample_ttest,
)
from cds.stats.regression import RegressionResult, linear_regression
from cds.stats.time_series import (
    LjungBoxResult,
    StationarityResult,
    autocorrelation,
    autocorrelation_function,
    difference,
    exponential_smoothing,
    kpss_statistic,
    ljung_box,
    moving_average,
    partial_autocorrelation,
    seasonal_decompose,
)

__all__ = [
    "mean",
    "median",
    "stdev",
    "variance",
    "correlation",
    "linear_regression",
    "RegressionResult",
    "TestResult",
    "one_sample_ttest",
    "two_sample_ttest",
    "chi_square_gof",
    "chi_square_independence",
    "one_way_anova",
    "t_sf",
    "chi2_sf",
    "f_sf",
    "cohens_d",
    "eta_squared_from_f",
    "cramers_v",
    "bonferroni_corrected_alpha",
    # Time-series analysis
    "autocorrelation",
    "autocorrelation_function",
    "partial_autocorrelation",
    "moving_average",
    "exponential_smoothing",
    "difference",
    "kpss_statistic",
    "seasonal_decompose",
    "ljung_box",
    "LjungBoxResult",
    "StationarityResult",
]
