"""Version metadata placeholder (regenerated by hatch-vcs at build time).

The real version is derived from the most recent v* git tag by hatch-vcs
at build time. This file is committed so that mypy can resolve __version__
in fresh clones (with no git history). The build hook overwrites it with
the actual version during ``python -m build`` and ``pip install -e .``.

When git tags are unavailable (e.g. shallow clones, sdists without history),
the build falls back to ``0.0.0+unknown`` — see ``fallback-version`` in
pyproject.toml.
"""
__version__ = "0.0.0+unknown"
